version: '3.8'

services:
  tasky-frontend:
    build: .
    container_name: tasky-frontend-dev
    ports:
      - "3001:3001"
    environment:
      - API_BASE_URL=http://localhost:8000
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge 