global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI application
  - job_name: 'tasky-api'
    static_configs:
      - targets: ['tasky-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Apache APISIX (if metrics work)
  - job_name: 'apisix'
    static_configs:
      - targets: ['apisix:9080']
    metrics_path: '/apisix/prometheus/metrics'
    scrape_interval: 5s
    
  # Fallback APISIX metrics
  - job_name: 'apisix-fallback'
    static_configs:
      - targets: ['nginx-metrics:80']
    metrics_path: '/metrics'
    scrape_interval: 15s 